FROM registry.fedoraproject.org/fedora-minimal:34

RUN microdnf -y install python3 && microdnf clean all

# !flask
# starlette
# starlette_sse
# kafka-python (pip3)
# python3-multipart (dnf)

ADD main.py /app/main.py
ADD animalid.py /app/animalid.py
ADD data.py /app/data.py

ENTRYPOINT ["python3", "/app/main.py"]
