apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-processor
  name: order-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: quay.io/skupper/trade-zoo-order-processor
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: cluster1-kafka-brokers:9092
