name: main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        skupper-version: [latest, main]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: manusa/actions-setup-minikube@v2.10.0
        with:
          minikube version: "v1.32.0"
          kubernetes version: "v1.29.0"
          github token: ${{secrets.GITHUB_TOKEN}}
      - run: curl https://skupper.io/install.sh | bash -s -- --version ${{matrix.skupper-version}}
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: ./plano test
        env:
          PLANO_COLOR: 1
