FROM registry.fedoraproject.org/fedora-minimal:36

RUN microdnf -y install gcc librdkafka-devel python3-devel python3-pip && microdnf clean all

RUN pip install starlette sse_starlette confluent_kafka uvicorn

COPY python /app/python

WORKDIR /app

ENTRYPOINT ["python3", "python/main.py"]
