name: main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: manusa/actions-setup-minikube@v2.6.0
        with:
          minikube version: "v1.25.2"
          kubernetes version: "v1.24.1"
          github token: ${{ secrets.GITHUB_TOKEN }}
      - run: curl -f https://skupper.io/install.sh | sh
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: ./plano test
